import type { Department, Project, MetadataEntity, ConnectionConfig, AutoUpdateSchedule } from '../types';

export const mockDepartments: Department[] = [
    {
        id: 'dept-1',
        name: 'Tổng Công ty',
        code: 'TCTCP',
        children: [
            {
                id: 'dept-1-1',
                name: 'Khối Kỹ thuật & Công nghệ',
                code: 'KKTCN',
                parentId: 'dept-1',
                children: [
                    { id: 'dept-1-1-1', name: 'Ban Công nghệ thông tin', code: 'BCNTT', parentId: 'dept-1-1' },
                    { id: 'dept-1-1-2', name: 'Ban Hạ tầng mạng', code: 'BHTM', parentId: 'dept-1-1' },
                    { id: 'dept-1-1-3', name: 'Ban An toàn thông tin', code: 'BATTI', parentId: 'dept-1-1' },
                ],
            },
            {
                id: 'dept-1-2',
                name: 'Khối Kinh doanh',
                code: 'KKD',
                parentId: 'dept-1',
                children: [
                    { id: 'dept-1-2-1', name: 'Ban Khách hàng doanh nghiệp', code: 'BKHDN', parentId: 'dept-1-2' },
                    { id: 'dept-1-2-2', name: 'Ban Khách hàng cá nhân', code: 'BKHCN', parentId: 'dept-1-2' },
                ],
            },
            {
                id: 'dept-1-3',
                name: 'Khối Tài chính',
                code: 'KTC',
                parentId: 'dept-1',
                children: [
                    { id: 'dept-1-3-1', name: 'Ban Kế hoạch tài chính', code: 'BKHTC', parentId: 'dept-1-3' },
                    { id: 'dept-1-3-2', name: 'Ban Kế toán', code: 'BKT', parentId: 'dept-1-3' },
                ],
            },
        ],
    },
];

export const mockProjects: Project[] = [
    { id: 'proj-1', name: 'Data Warehouse 2024', code: 'DWH2024', departmentId: 'dept-1-1-1', description: 'Xây dựng kho dữ liệu tập trung', status: 'ACTIVE' },
    { id: 'proj-2', name: 'Hệ thống CRM mới', code: 'CRM2024', departmentId: 'dept-1-2-1', description: 'Hệ thống quản lý khách hàng thế hệ mới', status: 'ACTIVE' },
    { id: 'proj-3', name: 'Nền tảng Analytics', code: 'ANLT2024', departmentId: 'dept-1-1-1', description: 'Phân tích dữ liệu nâng cao', status: 'ACTIVE' },
    { id: 'proj-4', name: 'Tích hợp IoT', code: 'IOT2024', departmentId: 'dept-1-1-2', description: 'Kết nối thiết bị IoT', status: 'INACTIVE' },
    { id: 'proj-5', name: 'Báo cáo tài chính tự động', code: 'BCTC2024', departmentId: 'dept-1-3-1', description: 'Tự động hóa báo cáo tài chính', status: 'ACTIVE' },
];

export const mockEntities: MetadataEntity[] = [
    {
        urn: 'urn:li:dataset:(urn:li:dataPlatform:mysql,viettel_dwh.khach_hang,PROD)',
        type: 'DATASET',
        name: 'khach_hang',
        platform: 'mysql',
        description: 'Bảng thông tin khách hàng doanh nghiệp',
        department: mockDepartments[0].children![1].children![0] as Department,
        project: mockProjects[1],
        owner: 'nguyen.van.a',
        tags: ['khách hàng', 'doanh nghiệp', 'PII'],
        status: 'ACTIVE',
        lastUpdated: '2024-06-10T08:00:00Z',
        createdAt: '2024-01-15T00:00:00Z',
    },
    {
        urn: 'urn:li:dataset:(urn:li:dataPlatform:postgresql,analytics.doanh_thu,PROD)',
        type: 'DATASET',
        name: 'doanh_thu',
        platform: 'postgresql',
        description: 'Dữ liệu doanh thu theo tháng, quý, năm',
        department: mockDepartments[0].children![2].children![0] as Department,
        project: mockProjects[4],
        owner: 'tran.thi.b',
        tags: ['tài chính', 'doanh thu', 'báo cáo'],
        status: 'ACTIVE',
        lastUpdated: '2024-06-11T10:30:00Z',
        createdAt: '2024-02-01T00:00:00Z',
    },
    {
        urn: 'urn:li:dashboard:(urn:li:dataPlatform:superset,dashboard_kpi,PROD)',
        type: 'DASHBOARD',
        name: 'Dashboard KPI Tháng',
        platform: 'superset',
        description: 'Bảng điều khiển KPI hàng tháng cho ban lãnh đạo',
        department: mockDepartments[0].children![0].children![0] as Department,
        project: mockProjects[2],
        owner: 'le.van.c',
        tags: ['KPI', 'báo cáo', 'lãnh đạo'],
        status: 'ACTIVE',
        lastUpdated: '2024-06-12T09:00:00Z',
        createdAt: '2024-03-01T00:00:00Z',
    },
    {
        urn: 'urn:li:dataset:(urn:li:dataPlatform:kafka,viettel.events.network,PROD)',
        type: 'DATASET',
        name: 'viettel.events.network',
        platform: 'kafka',
        description: 'Luồng sự kiện mạng viễn thông thời gian thực',
        department: mockDepartments[0].children![0].children![1] as Department,
        project: mockProjects[3],
        owner: 'pham.van.d',
        tags: ['mạng', 'real-time', 'IoT'],
        status: 'ACTIVE',
        lastUpdated: '2024-06-12T11:00:00Z',
        createdAt: '2024-04-01T00:00:00Z',
    },
    {
        urn: 'urn:li:dataset:(urn:li:dataPlatform:hive,dwh.dim_product,PROD)',
        type: 'DATASET',
        name: 'dim_product',
        platform: 'hive',
        description: 'Bảng chiều sản phẩm viễn thông',
        department: mockDepartments[0].children![0].children![0] as Department,
        project: mockProjects[0],
        owner: 'nguyen.thi.e',
        tags: ['DWH', 'dimension', 'sản phẩm'],
        status: 'ACTIVE',
        lastUpdated: '2024-06-09T14:00:00Z',
        createdAt: '2024-01-20T00:00:00Z',
    },
];

export const mockConnections: ConnectionConfig[] = [
    {
        id: 'conn-1',
        name: 'MySQL Production DWH',
        type: 'MYSQL',
        host: 'mysql-prod.viettel.internal',
        port: 3306,
        database: 'viettel_dwh',
        username: 'datahub_reader',
        ssl: true,
        status: 'CONNECTED',
        lastTestedAt: '2024-06-12T08:00:00Z',
    },
    {
        id: 'conn-2',
        name: 'PostgreSQL Analytics',
        type: 'POSTGRESQL',
        host: 'pg-analytics.viettel.internal',
        port: 5432,
        database: 'analytics',
        username: 'datahub_reader',
        ssl: true,
        status: 'CONNECTED',
        lastTestedAt: '2024-06-12T08:00:00Z',
    },
    {
        id: 'conn-3',
        name: 'Kafka Cluster',
        type: 'KAFKA',
        host: 'kafka.viettel.internal',
        port: 9092,
        username: '',
        ssl: false,
        status: 'DISCONNECTED',
        lastTestedAt: '2024-06-10T16:00:00Z',
    },
    {
        id: 'conn-4',
        name: 'Oracle Legacy DB',
        type: 'ORACLE',
        host: 'oracle-legacy.viettel.internal',
        port: 1521,
        database: 'VTDB',
        username: 'datahub_reader',
        ssl: false,
        status: 'ERROR',
        lastTestedAt: '2024-06-11T12:00:00Z',
    },
];

export const mockSchedules: AutoUpdateSchedule[] = [
    {
        id: 'sched-1',
        connectionId: 'conn-1',
        connectionName: 'MySQL Production DWH',
        frequency: 'DAILY',
        enabled: true,
        lastRunAt: '2024-06-12T02:00:00Z',
        nextRunAt: '2024-06-13T02:00:00Z',
        lastRunStatus: 'SUCCESS',
        retainHistory: 30,
    },
    {
        id: 'sched-2',
        connectionId: 'conn-2',
        connectionName: 'PostgreSQL Analytics',
        frequency: 'HOURLY',
        enabled: true,
        lastRunAt: '2024-06-12T11:00:00Z',
        nextRunAt: '2024-06-12T12:00:00Z',
        lastRunStatus: 'SUCCESS',
        retainHistory: 7,
    },
    {
        id: 'sched-3',
        connectionId: 'conn-3',
        connectionName: 'Kafka Cluster',
        frequency: 'DAILY',
        enabled: false,
        lastRunAt: '2024-06-10T02:00:00Z',
        nextRunAt: undefined,
        lastRunStatus: 'FAILED',
        retainHistory: 14,
    },
];
